version: "3.5"
services:
   jellyfin:
      image: jellyfin/jellyfin
      container_name: jellyfin
      user: 0:0
      network_mode: "host"
      restart: "unless-stopped"
      environment:
         - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
         - JELLYFIN_CONFIG_DIR=/etc/jellyfin
         - JELLYFIN_DATA_DIR=/var/lib/jellyfin
         - JELLYFIN_LOG_DIR=/var/log/jellyfin
      volumes:
         - /opt/jellyfin/etc:/etc/jellyfin
         - /opt/jellyfin/cache:/var/cache/jellyfin
         - /opt/jellyfin/lib:/var/lib/jellyfin
         - /opt/jellyfin/log:/var/log/jellyfin
         - type: volume
           source: nas-media-share
           target: /media
           volume:
              nocopy: true
   nzbget:
      image: lscr.io/linuxserver/nzbget
      container_name: nzbget
      network_mode: "host"
      restart: "unless-stopped"
      environment:
         - PUID=1000
         - PGID=1000
         - TZ=Europe/London
         - NZBGET_USER=nzbget #default username... to be changed...
         - NZBGET_PASS=tegbzn6789 #default password... to be changed...
      volumes:
         - /opt/nzbget/config:/config
         - /opt/nzbget/downloads:/downloads #optional
      ports:
         - 6789:6789
      
volumes:
   nas-media-share:
      driver_opts:
         type: cifs
         device: "${CIFS_PATH}"           
         o: "uid=0,username=${CIFS_USERNAME},password=${CIFS_PASSWORD},file_mode=0770,dir_mode=0770"
