version: "3"
services:
   jellyfin:
      image: jellyfin/jellyfin
      container_name: jellyfin
      user: 0:0
      network_mode: "host"
      restart: "unless-stopped"
      environment:
         - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
         - JELLYFIN_CONFIG_DIR=/etc/jellyfin
         - JELLYFIN_DATA_DIR=/var/lib/jellyfin
         - JELLYFIN_LOG_DIR=/var/log/jellyfin
      volumes:
         - /opt/jellyfin/etc:/etc/jellyfin
         - /opt/jellyfin/cache:/var/cache/jellyfin
         - /opt/jellyfin/lib:/var/lib/jellyfin
         - /opt/jellyfin/log:/var/log/jellyfin
         - /opt/jellyfin/media:/var/jellyfin/media

   nzbget:
      image: lscr.io/linuxserver/nzbget
      container_name: nzbget
      environment:
         - PUID=1000
         - PGID=1000
         - TZ=Europe/London
         - NZBGET_USER=nzbget #optional
         - NZBGET_PASS=tegbzn6789 #optional
      volumes:
         - /opt/nzbget/config:/config
         - /opt/nzbget/downloads:/downloads #optional
     #ports:
     #    - 6789:6789
      restart: unless-stopped
