# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job that runs "docker compose up"
  composedown:
    # The type of runner that the job will run on
    runs-on: [self-hosted, DockerHost]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # take down running service before starting the updated version  
      - name: Take down services described
        run: docker-compose down

      #create the .env file and print it for review
      - name: Get weird with github secrets
        run: |
          echo -e "CIFS_USERNAME=${{ secrets.CIFS_USERNAME }}\nCIFS_PASSWORD=${{ secrets.CIFS_PASSWORD }}\nCIFS_PATH=${{ secrets.CIFS_PATH }}" > .env
          cat .env

      # Runs a set of commands using the runners shell
      - name: Bring up services described
        run: docker-compose up

